name: Python CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for all branches
  push:
    branches: [ "**" ]
  # Triggers the workflow on pull request events targeting main or test branches
  pull_request:
    branches: [ main, test ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Run tests on multiple Python versions if needed
        python-version: ["3.10"] # Match requires-python in pyproject.toml

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Sets up the specified Python version
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Installs dependencies including development tools (pytest, ruff, build)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      # Runs the linter (Ruff)
      - name: Lint with Ruff
        run: |
          ruff check .

      # Runs the tests (pytest)
      - name: Test with pytest
        run: |
          pytest

      # Builds the source distribution and wheel
      # This verifies the package build process works
      - name: Build package
        run: python -m build